---

- hosts: all
  gather_facts: no
  tasks:
    - wait_for:
        port: 22
        delay: 10
    - name: ping all hosts
      ping:
    - name: Print env
      debug:
        var: env
    - name: Print dc
      debug:
        var: dc

- hosts: "CONSUL_{{ env }}_{{ dc }}"
  become: true
  roles:
    - role: brianshumate.consul

- hosts: "NOMAD_{{ env }}_{{ dc }}"
  become: true
  roles:
    - role: brianshumate.nomad

- hosts: "NOMAD_{{ env }}_{{ dc }}"
  become: true
  roles:
    - role: dggreenbaum.spatial-firewall
