---

- hosts: "CONSUL_{{ env }}_{{ dc }}:NOMAD_{{ env }}_{{ dc }}"
  gather_facts: no
  tasks:
    - wait_for:
        port: 22
        delay: 10

- hosts: "CONSUL_{{ env }}_{{ dc }}"
  roles:
    - role: dggreenbaum.openssl-pki

- hosts: "CONSUL_{{ env }}_{{ dc }}"
  become: true
  roles:
    - role: brianshumate.consul
  #   - role: franklinkim.environment


- hosts: "NOMAD_{{ env }}_{{ dc }}"
  become: true
  roles:
    - role: brianshumate.nomad
    - role: franklinkim.environment

- hosts: "NOMAD_{{ env }}_{{ dc }}"
  become: true
  roles:
    - role: dggreenbaum.spatial-firewall
